
server:
  port: 8080
spring:
  application:
    name: customer
  profiles:
    active: local
rabbitmq:
  exchanges:
    internal: internal.exchange
  routing-keys:
    internal-notification: internal.notification.routing-key